# Basic settings
title: "Grandes Modelos de Linguagem aplicados a Geração Aumentada via Recuperação"
description: "Esta página contém informações complementares à disciplina “Grandes Modelos de Linguagem aplicados a Geração Aumentada via Recuperação” do Programa de Pós-Graduação em Computação da Universidade Federal de Pelotas, ministrada em 2024/2 por Ricardo Matsumura Araújo."
theme: jekyll-theme-leap-day
url: "https://ricardoaraujo.github.io/ppgc_rag/"
show_github_button: false
